### ISSUE TITLE
no .ispac file found

### ISSUE THREAD

**Issue by jguaring** [ToxicGlobe/VSTS-SSIS-Extension#1]
Hi there, I'm using the extension for the first time and I'm getting an error message during the build "Test Output: No .ispac file found in "

I tried command line switch Deploy, Build and Rebuild but no luck.

Am I missing anything or any configuration that I need to setup?

TFS version (Version 15.105.25910.0)

**Comment by hariprabu2010** [comment]
Hi, I am having a similar issue. No error is reported. Build completes successfully but I cant find a ispac file in bin directory. I have tried a powershell script to list the contents of the build directory after the build is over, but I cant see any ispac files in the whole directory.

**Comment by schwaizi** [comment]
Hi, can you attach log files from VSTS please?
