### ISSUE TITLE
Error Installing on TFS 2015 Update 2.1

### ISSUE THREAD

**Issue by wegfel** [ToxicGlobe/VSTS-SSIS-Extension#1]
I tried to install it to TFS 2015 Update 2.1 Ver. 14.95.25229.0. I got "Extension manifest file format is invalid" error. Any help please.

**Comment by schwaizi** [comment]
Sorry, there is no support for someone who put bad review on other people's work without evaluating possible options before do so.  See your review here: https://marketplace.visualstudio.com/items?itemName=TG.VSTS-SSIS#review-details
Thanks for your understanding...

**Comment by schwaizi** [comment]
Sorry, as discussed - problem in your system.

**Comment by wegfel** [comment]
Sorry, What I did was an innocent mistake. I didn't try to give you review. I was asking the problem I faced problem in wrong place.Is there a way to delete what I wrote? The only option I get it to update it. Please let me know the possible ways to fix the review I wrote.
Sorry again.
Regards, Wegayehu Ayele 

    On Saturday, December 9, 2017 3:00 AM, schwaizi <notifications@github.com> wrote:
 

 Closed #1.—
