### ISSUE TITLE
Example on how to deploy to OnPrem

### ISSUE THREAD

**Issue by Ralbey** [ToxicGlobe/VSTS-SSIS-Extension#13]
Hi, 

We've been trying to deploy SSIS to an Azure VM. We can't seem to connect to the database. Is there any tutorial on how to achieve this?

Kind regards, 

Rutger

**Comment by schwaizi** [comment]
Hi Ralbey, you can get instructions how to configure the task in the Read.me file. Azure VM or onPremise should be no difference. If you can not connect the issue may be somewhere else (permission of the build agent account, firewall, etc). I would suggest to post log from VSTS. BR Peter
