### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by aand1173** [ToxicGlobe/VSTS-SSIS-Extension#15]
I don't know if this is a bug with my setup or the tool, but I'm going to assume it's my setup. 

I have a working build on my computer with VS2015. I have that checked into VS online and the solution and project files specified. However, when I run a hosted build I get the error below. I am not sure how to troubleshoot this.

Test Output: No .ispac file found in d:\a\1\s!

Do I need to install the SSDT on the build agent server, and if so how do I do that?
I also noticed that I didn't check in my \bin\development directories, does that matter?

**Comment by schwaizi** [comment]
Hi, i would suggest to attach the log from VSTS. Your issue is the Build task haven't created the ispac or it didn't found it. I can check that.

You can find the SSDT here: [Link](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt). Just run the setup, nothing specific if i remember correctly.

**Comment by aand1173** [comment]
Thank you for the quick response. We were able to figure out the problem. We needed to use the Hosted option, not Hosted 2017. Now the build is working and deploying as requested. This is awesome!

**Comment by schwaizi** [comment]
Perfect. Thank you for your feedback!

**Comment by schwaizi** [comment]
Hi, this issue was reported on VS Developer Community website as it seems to be problem with the Hosted VS2017 agent server image.

[link](https://developercommunity.visualstudio.com/content/problem/125489/devenevcom-on-hosted-vs2017-agent-not-able-to-buil.html)
