### ISSUE TITLE
SSIS Deploy - user and password

### ISSUE THREAD

**Issue by jcgc98** [ToxicGlobe/VSTS-SSIS-Extension#17]
Hello, 

This extension is great and is working fine for the compilation and deployment but the only thing is that you cannot specify the user name and password for the SQL connections string, i saw the code and it is hard code the integrated security SSPI.

is there any plan for adding those fields or can i get the code and add them my self?

Thanks,

**Comment by schwaizi** [comment]
Hi, thanks for your feedback and good suggestion for enhancement. Let me take a look on it, but can not confirm any delivery date yet.

**Comment by schwaizi** [comment]
Hi, i investigated option for SQL Authentication, unfortunately SSIS packages can not be deployed using SQL authentication. It need to be Windows Authentication because of Windows/SQL server Architecture.

This is the message when trying to deploy to remote server using SQL Authentication:

> Exception calling "DeployProject" with "2" argument(s): "The operation cannot be started by an account that uses SQL Server Authentication. Start the operation with an account that uses Windows Authentication."

**Comment by jcgc98** [comment]
Thanks for looking at it.


i didn't know that you need windows authentication.


the extension is great so far. i'm using it for CI/CD.


Thanks,

________________________________

**Comment by schwaizi** [comment]
Is not me who need it :) It is linked to MS architecture and security. I really did in details, but no easy solution. there has been option using Proxy Account, but this is specialized solution and out of scope for this free Extension.

**Comment by schwaizi** [comment]
and many thank for the feedback! You can eventually Review it on the Marketplace.
