### ISSUE TITLE
Not working with TFS 2017 Update 2 (on-prem) - No .ispac file found

### ISSUE THREAD

**Issue by sumo300** [ToxicGlobe/VSTS-SSIS-Extension#23]
We're getting the following error when trying to build an SSIS solution:

`Task_InternalError This command cannot be run due to the error: The system cannot find the file specified.
Test Output: No .ispac file found in D:\APPS\agent\_work\116\s!`

**Comment by schwaizi** [comment]
hi, please follow #22
