### ISSUE TITLE
Project Parameters Blank

### ISSUE THREAD

**Issue by rudisugi** [ToxicGlobe/VSTS-SSIS-Extension#3]
There is an error when we try to deploy SSIS with nothing set at the Project Parameters field. We made changes to workaround this problem in the powershell file (DeploySSISTask) line 76 to change from
if ($project.Parameters.Count -gt 0)
TO:
if ($ProjectParameters -ne '')

**Comment by schwaizi** [comment]
Hi, thanks for your feedback. The extension will get update and this issue has been fixed with IsNullOrWhiteSpace method.

**Comment by schwaizi** [comment]
updated on marketplace
