### ISSUE TITLE
No .ispac file found 

### ISSUE THREAD

**Issue by timgaspard** [ToxicGlobe/VSTS-SSIS-Extension#4]
Hey,

During build I get the following error: No .ispac file found in d:\a\1\s!
When executing the devenv statement. I get: 
The operation could not be completed. The parameter is incorrect
This is the executed statement:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Devenv.com "d:\a\1\s\CMS Migration EAN.sln" /rebuild release /project "d:\a\1\s\CMS Migration EAN\CMS Migration EAN.dtproj" /projectconfig release
I am quite new to this so I don't know if this is a bad configuration error from my side or a real issue.

Thanks in advance!

**Comment by siruvuru** [comment]
Open the solution file (.sln) and see what is the Active configuration, it looks like below and set $(BuildConfiguration)as that.

In my case, it is $(BuildConfiguration)=Development

```

Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Development|Default = Development|Default
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{DE9C37FA-6EE2-427A-B2B3-9403ADBC98BF}.Development|Default.ActiveCfg = **Development**
		{DE9C37FA-6EE2-427A-B2B3-9403ADBC98BF}.Development|Default.Build.0 = Development
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

**Comment by timgaspard** [comment]
Hi,

Thx for the response.

This seems to resolve the problem!

Thank you
