### ISSUE TITLE
SSIS Build & Deploy Extension Licence Issue.

### ISSUE THREAD

**Issue by RRGGSS** [ToxicGlobe/VSTS-SSIS-Extension#6]
Hello ToxicGlobe,
I have been using SSIS Build & Deploy Extension to build & deploy SSIS packages.
After I ran a build, I am seeing the following statement for the licence expiration as mentioned.

2017-11-15T20:40:01.8111216Z Name    : devenv.com
 2017-11-15T20:40:02.6731416Z Microsoft Visual Studio 2015 Version 14.0.25420.1.
 2017-11-15T20:40:02.6741298Z Copyright (C) Microsoft Corp. All rights reserved.
 2017-11-15T20:40:02.6741298Z The license for Visual Studio expires in 90 days.
Currently, I am having Visual Studio Client trail version. I just want to know am I really need to have licensed version of VS for these kind of Build & deploy jobs using extension SSIS Build & Deploy?
Thanks,
RGS

**Comment by schwaizi** [comment]
Hi, the extension is using part of VS (devenv.com) and i assume the message you posted is comming from the devenv.com which is telling you about expiration of your VS installation.

**Comment by RRGGSS** [comment]
Thank you Schwaizi!! I just want to understand whether i need to have licensed version of Visual Studio or not to run the SSIS Build & Deploy Extension successfully?
