### ISSUE TITLE
DeploySSIS task: Project parameters field not showing in TFS 2015

### ISSUE THREAD

**Issue by avdbrink** [ToxicGlobe/VSTS-SSIS-Extension#7]
First of all: great tasks! Thanks a million, if I had to figure this out myself I would have had no spare time left till the end of the year! :)
What I've noticed is that on our TFS2015 on premises setup the field for entering project parameters for the Deploy SSIS task did not show up. The label is shown as expected, but htere was no edit field next to it.
I looked in the task.json and on line 72 I changed "multiline" to "multiLine" 
This seems to fix the issue for me.
Hope this helps others too.

Keep up the good work!
Regards,
Arno

**Comment by schwaizi** [comment]
Hi Arno, first of all thank you for using the extension, testing and participating in the project!
Will be possible you will fix the bug in the code here on GitHub and then i'll run new release?

**Comment by avdbrink** [comment]
Hi,
I think I just edited the file, but I'm quite new to GitHub, so I'm not sure that my change was successful. Can you confirm?
Arno

**Comment by schwaizi** [comment]
well done! fixed by @avdbrink in #10
