### ISSUE TITLE
Unpublished on marketplace

### ISSUE THREAD

**Issue by phend2wj** [ToxicGlobe/VSTS-SSIS-Extension#8]
Why is this unpublished on the VSTS marketplace? Any plans to make it available again?

**Comment by schwaizi** [comment]
Hi, a bit uncomfortable situation for me when i see bad reviews on Marketplace for FREE extension from one user and in the same moment the same user is asking if i can provide the extension again. That's may be why i decided to un-publish the extension.

**Comment by phend2wj** [comment]
Any plans to make this extension available again?

**Comment by schwaizi** [comment]
it is available again with update
