### ISSUE TITLE
Error during deployment when no project parameters in the project

### ISSUE THREAD

**Issue by avdbrink** [ToxicGlobe/VSTS-SSIS-Extension#8]
When deploying a project that has no project parameters defined, an error occurs as the deploy script tries to iterate over the $project.Parameters collection which is then empty. 
file: DeploySSISTask.ps1 
line: 80 
I will propose a change where the script will check if the collection does not contain 0 entries and only then call the Contains method

**Comment by schwaizi** [comment]
fixed by @avdbrink in #9

**Comment by schwaizi** [comment]
Aaron Gibbs commented: There is a bug in the deploy task where it generates an error if you leave the "Parameters" box empty so you have to specify at least one parameter. Deployment works (but with a warning) if you just put an invalid value like "abcd"

**Comment by schwaizi** [comment]
Fixed in #12
